name: test-minimalist
on: [pull_request]

jobs:
  test:
    name: test-minimalist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          yarn
      - name: Lint Minimalist
        run: |
          yarn lint
      - name: Run Minimalist
        run: |
          yarn test
